CREATE SCHEMA IF NOt EXISTS `BOOKMANAGER` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS BOOKMANAGER.BOOK (
  ID INT NOT NULL AUTO_INCREMENT,
  BOOK_TITLE VARCHAR(255) NOT NULL,
  BOOK_AUTHOR VARCHAR(255) NOT NULL,
  BOOK_PRICE INT NOT NULL,
  PRIMARY KEY (ID));

INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('1', 'First Book', 'First Author', '30000');
INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('2', 'Second Book', 'Second Author', '20000');
INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('3', 'Third Book', 'Third Author', '15000');
INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('4', 'Fourth Book', 'Fourth Author', '25000');
INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('5', 'Fifth Book', 'Fifth Author', '80000');
INSERT IGNORE INTO BOOKMANAGER.BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('6', 'Sixth Book', 'Sixth Author', '50000');
